baseURL = "https://roberttilson.net"
title = "Robert Tilson's Blog"
copyright = "Powered by Hugo."

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "IT Blog of Robert Tilson"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Robert Tilson"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Robert Tilson"

[author.social]
  #codepen = "MunifTanjim"
  #facebook = "MunifTanjim"
  github = "rmtilson"
  #instagram = "instarobbie"
  twitter = "@tweetingTilson"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = -70
  identifier = "Home"
  url = "/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
